### ISSUE TITLE
Ribbon is not displayed on the Backoffice

### ISSUE THREAD

**Issue by haruka-7** [sap-commerce-tools/environment-ribbon#1] opened 2023-11-22 13:47 UTC
Hi @mpern !

Thanks for this extension ;) it works well on the HAC, but on the Backoffice the ribbon is not displayed.
I'm testing it on my local with Commerce 2211.

![image](https://github.com/sap-commerce-tools/environment-ribbon/assets/1431205/22f18197-08e7-49d1-a2d4-019775eefb0b)

![image](https://github.com/sap-commerce-tools/environment-ribbon/assets/1431205/fbf77eda-7091-4c72-82a8-5d8d2d1ff121)

**Comment by mpern** [comment] 2023-11-22 16:13
Thx for reporting!

I'll check early next week what the issue is. Probably need to adjust how the ribbon is configured as back office widget

**Comment by haruka-7** [comment] 2023-11-28 14:43
I do not why but it's working now :

![image](https://github.com/sap-commerce-tools/environment-ribbon/assets/1431205/d7d92ca1-755e-481a-922e-9025d43aa76c)

**Comment by mpern** [comment] 2023-11-28 15:19
Maybe you haven't reloaded the Backoffice config before?

**Comment by mpern** [comment] 2023-11-28 16:32
I'll close the issue, just open another one if required

**Closed as completed by mpern** 2023-11-28 16:32 UTC

**Comment by mpern** [comment] 2023-11-28 17:00
https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/9b5366ff6eb34df5be29881ff55f97d2/8c3dfc2486691014b115a842456ad0a5.html?locale=en-US
